# Generated by Django 5.1.1 on 2024-10-31 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_token_no'),
        ('appointment_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Queue_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment_queue.appointmentqueue'),
            preserve_default=False,
        ),
    ]
