# Generated by Django 5.1.1 on 2024-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_queue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Approx_Time',
            field=models.CharField(default='8:11 AM'),
            preserve_default=False,
        ),
    ]
