# Generated by Django 5.1.1 on 2024-10-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_alter_doctor_rating'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentQueue',
            fields=[
                ('Queue_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.CharField(max_length=255)),
                ('Current_Number', models.BigIntegerField(null=True)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
