# Generated by Django 5.1.1 on 2024-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='Current_Number',
            field=models.BigIntegerField(default=1),
        ),
    ]
