# Generated by Django 5.1.1 on 2024-11-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('Medicine_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medicine.medicine')),
                ('Interval', models.CharField(max_length=255)),
                ('Times_per_day', models.IntegerField()),
                ('Monday', models.BooleanField(default=False)),
                ('Tuesday', models.BooleanField(default=False)),
                ('Wednesday', models.BooleanField(default=False)),
                ('Thursday', models.BooleanField(default=False)),
                ('Friday', models.BooleanField(default=False)),
                ('Saturday', models.BooleanField(default=False)),
                ('Sunday', models.BooleanField(default=False)),
                ('Before_meal', models.BooleanField(default=False)),
                ('After_meal', models.BooleanField(default=False)),
                ('Quantity', models.CharField(max_length=255)),
                ('Turn_off_after', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
            ],
        ),
    ]
