# Generated by Django 5.1.1 on 2024-11-02 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_remove_doctor_current_hos_doctor_current_hos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Prescription_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Progress', models.CharField(default='0%', max_length=50)),
                ('IsHide', models.BooleanField(default=False)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
