# Generated by Django 5.1.1 on 2024-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescription_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Date',
            field=models.CharField(),
        ),
    ]
