# Generated by Django 5.1.1 on 2024-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Medicine', models.CharField(max_length=255)),
                ('Quantity', models.CharField(max_length=255)),
                ('Strength', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
            ],
        ),
    ]
