# Generated by Django 5.1.1 on 2024-11-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Prescription_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription'),
        ),
    ]
