# Generated by Django 5.1.1 on 2024-11-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('Notification_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.CharField()),
                ('Note', models.TextField()),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
