# Generated by Django 5.1.1 on 2024-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('Keyword_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Keyword', models.CharField(max_length=255)),
            ],
        ),
    ]
