# Generated by Django 5.1.1 on 2024-11-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('Reminder_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('before_meal', models.BooleanField(default=False)),
                ('after_meal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('Medicine_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('Pharmacy_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy')),
            ],
        ),
    ]
