# Generated by Django 5.1.1 on 2024-11-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='Pharmacy_ID',
        ),
    ]
