# Generated by Django 5.1.1 on 2024-11-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Other_name', models.CharField(max_length=255)),
                ('Birthday', models.CharField(max_length=255)),
                ('Street_No', models.CharField(max_length=255)),
                ('Street_Name', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Postal_Code', models.CharField(max_length=255)),
                ('NIC', models.CharField(max_length=20)),
                ('Reg_num', models.CharField()),
                ('Specialization', models.CharField(max_length=255)),
                ('Rating', models.FloatField(default=0.0)),
                ('Availability', models.BooleanField(default=True)),
                ('ID_photo', models.BigIntegerField(null=True)),
                ('Current_HOS_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
