# Generated by Django 5.1.1 on 2024-11-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Patient_Count',
            field=models.BigIntegerField(default=0),
        ),
    ]
