# Generated by Django 5.1.1 on 2024-11-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_patient_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Rating_Count',
            field=models.BigIntegerField(default=0),
        ),
    ]
